[package]
name = "queueing-model"
version = "0.1.0"
authors = ["vegtamr <barekov.am.v@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.6.0"
itertools = "0.9.0"
rand = "0.7.3"